### ISSUE TITLE
Принести 600 гаргулек!

### ISSUE THREAD

**Issue by Ikomas** [SamTyurenkov/punker#1]
Приветствую! Я дохожу до последнего игрока, а система требует, чтобы я принес 600 гаргулек, чтобы до него добраться. Прирост в единственной имеющейся башне - в районе 20 в неделю. Неужели нужно ждать 8 месяцев и ничего не делать, чтобы добраться до последнего оппонента?
![problem](https://user-images.githubusercontent.com/48919920/63436039-a9567280-c430-11e9-8c08-d2113bf45de0.jpg)

**Comment by SamTyurenkov** [comment]
Хмм, спасибо за комментарий. Подумаю на этот счет. Если стоять возле прохода, то противник может сам выйти к вам. Это ограничение скорее для него, чтобы он не набрал много лазурных драконов раньше времени. 

Правда я не учел, что можно пройти за 3 месяца и самому упереться в этот блок. 
На какой сложности вы прошли за 3 месяца?

**Comment by Ikomas** [comment]
160 процентов.  И было отчетливое ощущение, что сложность в процессе игры уменьшается. То есть, когда какой-нибудь Фафнер вообще не оказывает сопротивления и умирает с двух армагеддонов, возникает странное чувство. 

И еще есть некоторые вопросы, касательно игровой механики: 
1) Зачем нужно освобождать героя Оплота, которому нужно принести оковы войны? Я думал, что будет какой-то страж, проход которого открывается при смерти этого героя, но нет. Он просто дает артефакты, 
2) В хижине провидца на воде за 30 уровень дают 2 силы магии. Так и должно быть? Какая-то странная награда, на мой взгляд. 
3) В игре огромное количество шахт за сильными охранами, которые можно и не пробивать. Ресурсов и так будет в достатке (см. скриншот в начале топика)

По прохождению - на третьей неделе можно спокойно дойти до соседних варваров (за 100 гоблинов), убить их и взять 3 сказочных драконов. С ними и магией (эксперт земля, воскрешение и стрелочка) все остальные оппоненты (до открытия тюрьмы на воде) легко умирают (сказочные танкуют, армия уничтожается стрелочкой, сказочные воскрешаются -> цикл повторяется). После открытия тюрьмы появляется герой с экспертным огнем (берсерк, призыв огневиков, армагеддон) и он уже может практически без армии уничтожать все живое.

**Comment by SamTyurenkov** [comment]
Спасибо за комментарии. А версия игры у вас HotA, верно? Не вижу пиратского замка на скриншоте. И еще вопрос, можете ли вы сказать что вам где то сильно повезло - кто-то присоединился к армии в начале?

 Я сам не очень хорошо играю, хотя у тех, кто играет хорошо карта заняла все же больше времени. 

Горгулий учту (думаю добавить их в реварды за победу над Фафнером), а по остальным пунктам: 
1) Да, этот герой - побочная драка. Он не важен по сюжету.
2) Ну тоже не баг в общем. А что именно вам кажется странным?
3) Согласен, экономику можно сделать и пожестче в середине и конце игры, а как? События с потерей ресурсов случайные? 
4) Разве варвары вас не убивают на третьей неделе? там же сильный орк. а эльфы вроде тоже легко убивают 3х сказочных драконов.

Как именно вы советуете понерфить огонь? Совсем выпиливать не хочется, все же это допустимая механика.

**Comment by Ikomas** [comment]
Да, Хота, последней версии. 
Пиратский замок есть, но он ниже, я его захватывал после Инферно.

Я играл без дипломатии и за всю игру (практически в самом конце) ко мне присоединились только зеленые драконы (когда это было уже не нужно).

2. Странным кажется то, что игра спокойно проходится без столь высокого уровня (30). На момент скриншота мой максимальный уровень героя - 25. Чтобы посмотреть награду (я думал, там гаргульки будут) пришлось бегать по всей карте и собирать деревья уровней. Та  и прибавка к мощности героя (+2) при статах под 60 кажется вообще незначительной. 

На счет экономики: в середине и в конце игры есть магия и экономика вообще не важна. А в начале - да. Например, у варваров была свободная шахта кристаллов (без охраны вообще, может они ее сами пробили). Также на карте есть рынок с хорошим обменным курсом. И в Оплотах есть сокровищницы, которые обеспечивают просто колоссальный приход денег. 

Первый эльфийский замок захватывается без проблем (сейчас посмотрел, там нет сильного героя вообще), затем идет орк: До того, как открыть столбик, ИИ не видит нашего героя и считает, что он находится вне досягаемости. Поэтому, он спокойно бегает по карте не думая о нас. То есть, если завершить ход прямо перед столбиком , то на следующий ход можно сесть во вражеский замок, а на ход оппонента методом башен, циклопов и чародеев его расстрлять.

Потом после первого орка умирает второй, затем захватывается Данж, удваивается мана и на момент второго Оплота у героя уже 5 или 6 сказочных, не помню точно. А они очень неплохо танкуют, особенно под Щитом и Каменной кожей. 

Можно запретить либо заклинание вызова огненых элементалей, либо армагеддон, тогда их связка не будет работать. Запрет Элементалей - интереснее, но добиться баланса будет сложнее ибо армагеддон можно использовать с золотыми либо черными драконами в армии (черный дракон -> наш герой ходит первым -> Армагеддон -> Большая часть вражеской армии мертва)

Кстати, в пандоре за достаточно сильной охраной мы получаем книгу магии воды. Не особо понимаю, зачем это нужно. По крайней мере, я ей ни разу не воспользовался в дальнейшем.

**Comment by Ikomas** [comment]
https://yadi.sk/d/qXOAJSGirFqKaA
Тут сейв битвы с Фафнером, можете сами протестировать эффективность двух армагеддонов :)

**Comment by SamTyurenkov** [comment]
Получилось комбо конечно из того, что вы действительно быстро прошли до них + сила заклинания. Со временем он бы накопил армию и два армагеддона бы не имели такого эффекта. 

В общем армагеддон я решил выпилить. Добавил гаргуль в награды за убийство Фафнера. Немного усложнил доступ к Сказочным драконам, но не сильно. 

Остальные моменты считаю вполне себе честными. Кстати армагеддон мог и не выпасть в замке при прохождении. Тут есть некоторый рандом.
